### PR TITLE
Add /api/v2/groups endpoints + tests

### PR DESCRIPTION
**Pull request by igaponov**

### CODE REVIEW

**Comment by austinpapp** [comment]
@igaponov please rebase and resolve conflicts. thanks!

**Comment by austinpapp** [comment]
i _think_ methods `getUserGroupsAction()` and `getGroupsAction()` are doing the same thing as they both return the user's groups. can you confirm this?

**Comment by igaponov** [comment]
@austinpapp I've checked it deeper and noticed, that getGroupsAction() returns all groups (`$user` parameter is not used), but getUserGroupsAction() returns only user's groups. Do we need the first one?

**Comment by austinpapp** [comment]
we definitely want them both. the first one is useful for looking at another users profile. eventually the groups will have public and private visibility which is set by that group's leader. we just need to make sure the endpoints are unique enough and documentation is up to date so that we understand the specific distinction between them. thanks for looking into that.

**Comment by austinpapp** [comment]
i dont see any need to move this into the public api at least for right now. @jterps08 any thoughts here? to get another user's groups list (not your own), do we want that to be behind authentication or publicly available?

**Comment by austinpapp** [comment]
@igaponov when you get a chance can you just update the documentation so that its more obvious the two endpoints are in fact different? thanks!

**Comment by igaponov** [comment]
@austinpapp updated

**Pull request merged**
