### PR TITLE
Support of Api multi-login entities

### PR DESCRIPTION
**Pull request by shakaran**
This PR allows multiple logins in api secure controller. Example in vagrant dev enviroment:

	curl -i -X POST -H 'application/x-www-form-urlencoded' -G 'http://192.168.10.100/api/secure/login' -d 'username=admin&password=admin'

	HTTP/1.1 200 OK
	Server: nginx/1.4.6 (Ubuntu)
	Content-Type: application/json
	Transfer-Encoding: chunked
	Connection: keep-alive
	Cache-Control: no-cache
	Date: Wed, 16 Mar 2016 13:23:02 GMT
	Access-Control-Allow-Origin: *
	Access-Control-Allow-Headers: accept, origin, x-requested-with, token, content-type
	X-Debug-Token: 426a08

	{"token":"26z1pru3421ww0k4s4g44so488owk8ggow8kc0c88k0w8swwcc1"}

This allows login to users, groups, representatives and superusers in that order.

In case that we have conflict naming, the left entity has priority over the right entity in that order. As future improvement if we are agree we can use a optional param called "type" for indicate the entity type in case of naming conflict.

Note that this PR will require a update of schema database with:

    php app/console doctrine:schema:update --force

And this PR only should be merged after PR #83 will be merged since it is a dependancy.

### CODE REVIEW

**Comment by habibillah** [comment]
> Note that this PR will require a update of schema database with:
>
>     php app/console doctrine:schema:update --force

Is it imposible to use db migration?

**Comment by shakaran** [comment]
@habibillah we can use db migration for add the field of course, but since it is not a change of type of column or some complex operation over a table or so, I think that it is just spend time in write a migration file if doctrine already automatize this change for us. 

Schema updates vs migrations is a good topic to discuss, probably I would not do this if the change was in a big table or with a lot users, or if the project was in a stage very advanced, but now I think that it is pretty safe add this command in the deploy script. With:

    php app/console doctrine:schema:update --dump-sql

You can see exactly that it will make the same sql queries than a migration. The only disavantage would be rollback that changes, that in this case should be not needed, since it is a must change for progress.

**Comment by igormukhingmailcom** [comment]
Guys, never use `php app/console doctrine:schema:update` on production please.
Any changes should be prepared via migration files.

**Comment by igaponov** [comment]
and `php app/console doctrine:migration:diff` creates migration automatically

**Comment by shakaran** [comment]
ok, for popular petition, added the autogenerated migration :+1:

**Comment by austinpapp** [comment]
handled by #93

**Pull request closed without merging**
