### PR TITLE
don't not hardcode the activity type

### PR DESCRIPTION
**Pull request by habibillah**
Re-factor the activity type. change the hard coded `type` to several`const` to minimalize the hard coded data.

### CODE REVIEW

**Comment by austinpapp** [comment]
@habibillah can you rebase and fix any conflicts for me? i'll merge after.

**Comment by habibillah** [comment]
xdone

**Comment by austinpapp** [comment]
it looks like you are trying to recommit previous commits...

**Comment by habibillah** [comment]
replaced #223

**Pull request closed without merging**
