### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by shakaran**
Small cosmetic changes, updates in DataFixtures and use consitency with fully qualified class name in repostitory classes

### CODE REVIEW

**Comment by austinpapp** [comment]
@shakaran is this PR in a usable state? meaning, if i merge it into our develop branch, will the api function as expected? your enhancements seem cosmetic, igor's seem more disruptive so i just need to know the state of the PR. thanks for the work!

**Comment by shakaran** [comment]
@austin this PR could be merged (but maybe only cherry picking my commits,
since I cannot ensure about the Igor commits). I just merge the Igor's
changes in this branch since I need the Igor changes for use the Vagrant
deployment and testing

**Comment by austinpapp** [comment]
@shakaran if you have not tested igor's commits, please reissue this pull request with your work only. if you need igor's `Vagrantfile` work, just copy the 1 line of code... the `README.md` can always be updated later.

**Comment by shakaran** [comment]
Ok, closing this in favor of PR #29

**Pull request closed without merging**
