### PR TITLE
Fix JSON response in android endpoint test

### PR DESCRIPTION
**Pull request by shakaran**
This fix the error running the following unit test:

	1) Civix\CoreBundle\Tests\Entity\Notification\AndroidEndpointTest::testPlatformMessage
	Failed asserting that two strings are equal.
	--- Expected
	+++ Actual
	@@ @@
	-'{"GCM":"{\"data\":{\"message\":\"test_message\",\"type\":\"test_type\",\"entity\":\"null\",\"title\":\"test_title\",\"image\":null,\"actions\":[]}}"}'
	+'{"GCM":"{\"data\":{\"message\":\"test_message\",\"type\":\"test_type\",\"entity\":\"null\",\"title\":\"test_title\",\"image\":null}}"}'

	/vagrant/backend/src/Civix/CoreBundle/Tests/Entity/Notification/AndroidEndpointTest.php:17
	/usr/share/php/PHPUnit/TextUI/Command.php:176
	/usr/share/php/PHPUnit/TextUI/Command.php:129

I assume that the actions field is legit and probably this missing field was only forgotten to update in test

### CODE REVIEW

**Comment by habibillah** [comment]
keep this test fail. since the related code is incomplete and waiting from several info from mobile developer. see [this one](https://github.com/PowerlineApp/powerline-server/pull/56)

**Comment by shakaran** [comment]
@habibillah we should then wait to close this PR until @austinpapp decide which is the proper way to handle this. Develop don't should contain break or failing test pushed. At least we should mark this test as skipped with $this->markTestSkipped('Incomplete and waiting for several info from mobile developer'); so reopening for wait Austin input

**Comment by habibillah** [comment]
use `markTestIncomplete` instead.

**Comment by shakaran** [comment]
@habibillah updated, waiting merge approval from @austinpapp

**Pull request merged**
