### PR TITLE
Add an endpoint to get post analytics

### PR DESCRIPTION
**Pull request by igaponov**
https://github.com/PowerlineApp/powerline-mobile/issues/600

### CODE REVIEW

**Comment by jterps08** [comment]
really exciting - I'm looking forward to testing this. Is there any way that we can simulate a scenario at high volume to emulate the results? @igaponov

**Comment by igaponov** [comment]
@jterps08 use fake generated data? Maybe we can add a lot of votes for some post manually in db.

**Comment by jterps08** [comment]
Can you think about this (no action yet)? I think we need to figure out a way to simulate a large volume of action on a given trade across a large volume of fake users. Perhaps we could create a small tool that registers users in staging using a base set of input addresses (eg 25 addresses that I would provide) and would register X users per address and randomly assign a vote value to a particular post? Maybe that's more complicated than it needs to be. If you give me an XLS with the representatives in one sheet and the format of the db table that associates votes to representatives in another sheet, I can have one of the interns fabricate the data....@igapanov let me know on slack

**Comment by igaponov** [comment]
@jterps08 this is possible of course. Don't understand what XLS you want. The relation between votes and representatives: vote -> user -> district -> representative.

**Pull request merged**
